export const ADD_CONTEST_LOADING = "ADD_CONTEST_LOADING";
export const ADD_CONTEST_SUCCESS = "ADD_CONTEST_SUCCESS";
export const ADD_CONTEST_ERROR = "ADD_CONTEST_ERROR";

export const GET_CONTEST_LOADING = "GET_CONTEST_LOADING";
export const GET_CONTEST_SUCCESS = "GET_CONTEST_SUCCESS";
export const GET_CONTEST_ERROR = "GET_CONTEST_ERROR";
export const DELETE_CONTEST = "DELETECONTEST";
export const SORTDATE = "SORTDATE";
export const SORTDSA = "SORTDSA";
export const SORTCODING = "SORTCODING";
